package com.skapp.enterprise.peopleplanner.type;

public enum EpEmployeeTimelineType {

	JOB_FAMILY_ASSIGNED, JOB_FAMILY_CHANGED, JOB_TITLE_ASSIGNED, JOB_TITLE_CHANGED, EMPLOYMENT_TYPE_ADDED,
	EMPLOYMENT_TYPE_CHANGED, TEAM_ASSIGNED, TEAM_CHANGED, TEAM_REMOVED, EMPLOYMENT_ALLOCATION_ADDED,
	EMPLOYMENT_ALLOCATION_CHANGED, PRIMARY_SUPERVISOR_ASSIGNED, PRIMARY_SUPERVISOR_CHANGED,
	SECONDARY_SUPERVISOR_ASSIGNED, SECONDARY_SUPERVISOR_CHANGED, ENTITLEMENT_ADDED, ENTITLEMENT_UPDATED,
	CUSTOM_ALLOCATION_ADDED, CUSTOM_ALLOCATION_UPDATED, CUSTOM_ALLOCATION_REMOVED, PROBATION_START_DATE_ADDED,
	PROBATION_START_DATE_CHANGED, PROBATION_END_DATE_ADDED, PROBATION_END_DATE_CHANGED, JOINED_DATE_ADDED,
	JOINED_DATE_CHANGED, SYSTEM_PERMISSION_GRANTED, SYSTEM_PERMISSION_CHANGED

}
