export enum CrmModalTypes {
  ADD_COMPANY_MODAL = "ADD_COMPANY_MODAL",
  ADD_CONTACT_MODAL = "ADD_CONTACT_MODAL",
  EDIT_COMPANY_MODAL = "EDIT_COMPANY_MODAL",
  ADD_TASK_MODAL = "ADD_TASK_MODAL",
  DELETE_COMPANY_MODAL = "DELETE_COMPANY_MODAL",
  ADD_DEAL_STAGE_MODAL = "ADD_DEAL_STAGE_MODAL",
  EDIT_DEAL_STAGE_MODAL = "EDIT_DEAL_STAGE_MODAL"
}
