export enum CrmModalTypes {
  ADD_COMPANY_MODAL = "ADD_COMPANY_MODAL",
  DELETE_COMPANY_CONFIRMATION = "DELETE_COMPANY_CONFIRMATION"
}

export enum CrmDealModalTypes {
  CONFIRM_DELETE = "CONFIRM_DELETE",
  NONE = "NONE"
}
