export enum TriggerTypeEnum {
  ON_LOGIN = "ON_LOGIN",
  ON_FIRST_VISIT = "ON_FIRST_VISIT",
  ON_EVERY_VISIT = "ON_EVERY_VISIT",
  IMMEDIATELY_ON_PUBLISH = "IMMEDIATELY_ON_PUBLISH"
}

export enum FrequencyTypeEnum {
  ONE_TIME = "ONE_TIME",
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  CUSTOM = "CUSTOM"
}

export enum AnnouncementStatusEnum {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE"
}

export enum TargetPageEnum {
  DASHBOARD = "DASHBOARD",
  PEOPLE = "PEOPLE",
  LEAVE = "LEAVE",
  ATTENDANCE = "ATTENDANCE",
  TIMESHEET = "TIMESHEET",
  PROJECTS = "PROJECTS",
  ROLES = "ROLES",
  SETTINGS = "SETTINGS"
}

export enum AnnouncementInteractionTypeEnum {
  VIEWED = "VIEWED",
  DISMISSED = "DISMISSED",
  CTA_CLICKED = "CTA_CLICKED"
}

export enum AnnouncementRecipientRoleEnum {
  SUPER_ADMIN = "SUPER_ADMIN",
  PEOPLE_ADMIN = "PEOPLE_ADMIN",
  PEOPLE_MANAGER = "PEOPLE_MANAGER",
  PEOPLE_EMPLOYEE = "PEOPLE_EMPLOYEE",
  LEAVE_ADMIN = "LEAVE_ADMIN",
  LEAVE_MANAGER = "LEAVE_MANAGER",
  LEAVE_EMPLOYEE = "LEAVE_EMPLOYEE",
  ATTENDANCE_ADMIN = "ATTENDANCE_ADMIN",
  ATTENDANCE_MANAGER = "ATTENDANCE_MANAGER",
  ATTENDANCE_EMPLOYEE = "ATTENDANCE_EMPLOYEE",
  ESIGN_ADMIN = "ESIGN_ADMIN",
  ESIGN_SENDER = "ESIGN_SENDER",
  ESIGN_EMPLOYEE = "ESIGN_EMPLOYEE",
  INVOICE_ADMIN = "INVOICE_ADMIN",
  INVOICE_MANAGER = "INVOICE_MANAGER",
  INVOICE_NONE = "INVOICE_NONE",
  PM_ADMIN = "PM_ADMIN",
  PM_EMPLOYEE = "PM_EMPLOYEE",
  PM_GUEST_EMPLOYEE = "PM_GUEST_EMPLOYEE"
}
