export enum CommonModalType {
  NONE = "NONE",
  CREATE_FOLDER = "CREATE_FOLDER",
  RENAME_FOLDER = "RENAME_FOLDER",
  UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT",
  DELETE_DOCUMENT = "DELETE_DOCUMENT",
  MOVE_DOCUMENT = "MOVE_DOCUMENT",
  FOLDER_NOT_EMPTY = "FOLDER_NOT_EMPTY",
  ADD_BUSINESS_UNIT = "ADD_BUSINESS_UNIT",
  EDIT_BUSINESS_UNIT = "EDIT_BUSINESS_UNIT"
}
