export enum CrmPriorityEnum {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH"
}

export enum CrmIndustryEnum {
  NONE = "NONE",
  ACCOMMODATION_SERVICES = "ACCOMMODATION_SERVICES",
  ADMINISTRATIVE_AND_SUPPORT_SERVICES = "ADMINISTRATIVE_AND_SUPPORT_SERVICES",
  CONSTRUCTION = "CONSTRUCTION",
  CONSUMER_SERVICES = "CONSUMER_SERVICES",
  EDUCATION = "EDUCATION",
  ENTERTAINMENT_PROVIDERS = "ENTERTAINMENT_PROVIDERS",
  FARMING_RANCHING_FORESTRY = "FARMING_RANCHING_FORESTRY",
  FINANCIAL_SERVICES = "FINANCIAL_SERVICES",
  GOVERNMENT_ADMINISTRATION = "GOVERNMENT_ADMINISTRATION",
  HOLDING_COMPANIES = "HOLDING_COMPANIES",
  HOSPITALS_AND_HEALTH_CARE = "HOSPITALS_AND_HEALTH_CARE",
  MANUFACTURING = "MANUFACTURING",
  OIL_GAS_AND_MINING = "OIL_GAS_AND_MINING",
  PROFESSIONAL_SERVICES = "PROFESSIONAL_SERVICES",
  REAL_ESTATE_AND_EQUIPMENT_RENTAL_SERVICES = "REAL_ESTATE_AND_EQUIPMENT_RENTAL_SERVICES",
  RETAIL = "RETAIL",
  TECHNOLOGY_INFORMATION_AND_MEDIA = "TECHNOLOGY_INFORMATION_AND_MEDIA",
  TRANSPORTATION_LOGISTICS_SUPPLY_CHAIN_AND_STORAGE = "TRANSPORTATION_LOGISTICS_SUPPLY_CHAIN_AND_STORAGE",
  UTILITIES = "UTILITIES",
  WHOLESALE = "WHOLESALE"
}

export enum CrmPriorityEnum {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH"
}

export enum CrmDealSortEnum {
  CREATED_DATE = "CREATED_DATE",
  NAME = "NAME",
  CLOSING_AT = "CLOSING_AT",
  AMOUNT = "AMOUNT",
  STAGE_TYPE = "STAGE_TYPE",
  STAGE_ORDER = "STAGE_ORDER"
}

export enum CrmDealStageEnum {
  INITIAL = "INITIAL",
  OPEN = "OPEN",
  WON = "WON",
  LOST = "LOST"
}

export enum CrmTaskStatusEnum {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED"
}

export enum CrmDealSortEnum {
  CREATED_DATE = "CREATED_DATE",
  NAME = "NAME",
  CLOSING_AT = "CLOSING_AT",
  AMOUNT = "AMOUNT",
  STAGE_TYPE = "STAGE_TYPE",
  STAGE_ORDER = "STAGE_ORDER"
}
