package com.skapp.community.common.type;

public enum NotificationType {

	LEAVE_REQUEST, LEAVE_ENTITLEMENT, TIME_ENTRY, HOLIDAY, PASSWORD_RESET, LEAVE_REQUEST_NUDGE,
	DOCUMENT_SIGN_REQUEST, DOCUMENT_COMPLETED, DOCUMENT_DECLINED, DOCUMENT_VOIDED, DOCUMENT_REMINDER, DOCUMENT_EXPIRED

}
