package com.skapp.community.common.type;

public enum NotificationType {

	LEAVE_REQUEST, LEAVE_ENTITLEMENT, TIME_ENTRY, HOLIDAY, PASSWORD_RESET, LEAVE_REQUEST_NUDGE,
	ESIGN_DOCUMENT_SIGN_REQUEST, ESIGN_DOCUMENT_COMPLETED, ESIGN_DOCUMENT_DECLINED, ESIGN_DOCUMENT_VOIDED,
	ESIGN_DOCUMENT_REMINDER, ESIGN_DOCUMENT_EXPIRED

}
