import { CrmStore } from "./StoreTypes";

export interface CrmDataSliceTypes extends Pick<
  CrmStore,
  | "companies"
  | "contacts"
  | "deals"
  | "board"
  | "tasks"
  | "owners"
  | "stages"
  | "taskTypes"
  | "companyIds"
  | "contactIds"
  | "dealIds"
  | "taskIds"
  | "stageIds"
  | "setCompanies"
  | "setContacts"
  | "setDeals"
  | "setBoardColumn"
  | "setTasks"
  | "setOwners"
  | "setStages"
  | "setTaskTypes"
> {}

export interface CrmUiSliceTypes extends Pick<
  CrmStore,
  | "companyIds"
  | "contactIds"
  | "dealIds"
  | "taskIds"
  | "stageIds"
  | "isCompanyModalOpen"
  | "companyModalType"
  | "isContactModalOpen"
  | "contactModalType"
  | "isTaskModalOpen"
  | "taskModalType"
  | "selectedCompanyId"
  | "selectedContactId"
  | "selectedDealId"
  | "selectedTaskId"
  | "isCrmSidePanelOpen"
  | "crmSidePanelType"
  | "preselectedStageId"
  | "setIsCompanyModalOpen"
  | "setCompanyModalType"
  | "setIsContactModalOpen"
  | "setContactModalType"
  | "setIsTaskModalOpen"
  | "setTaskModalType"
  | "setSelectedCompanyId"
  | "setSelectedContactId"
  | "setSelectedDealId"
  | "setSelectedTaskId"
  | "openCrmSidePanel"
  | "closeCrmSidePanel"
  | "setPreselectedStageId"
> {}
