export const SKILL_OPTIONS = [
  { id: 1, label: "Python Programming" },
  { id: 2, label: "JavaScript Development" },
  { id: 3, label: "Java Programming" },
  { id: 4, label: "C++ Programming" },
  { id: 5, label: "C# Programming" },
  { id: 6, label: "TypeScript" },
  { id: 7, label: "Go (Golang)" },
  { id: 8, label: "Rust Programming" },
  { id: 9, label: "Ruby on Rails" },
  { id: 10, label: "PHP Development" },
  { id: 11, label: "Swift Programming" },
  { id: 12, label: "Kotlin Development" },
  { id: 13, label: "React.js" },
  { id: 14, label: "Angular Framework" },
  { id: 15, label: "Vue.js" },
  { id: 16, label: "Node.js" },
  { id: 17, label: "Django Framework" },
  { id: 18, label: "Spring Boot" },
  { id: 19, label: "RESTful API Design" },
  { id: 20, label: "GraphQL" },
  { id: 21, label: "Microservices Architecture" },
  { id: 22, label: "Docker" },
  { id: 23, label: "Kubernetes" },
  { id: 24, label: "CI/CD Pipelines" },
  { id: 25, label: "Git Version Control" },
  { id: 26, label: "Agile Development" },
  { id: 27, label: "Test-Driven Development" },
  { id: 28, label: "Unit Testing" },
  { id: 29, label: "Code Review" },
  { id: 30, label: "System Design" },
  { id: 31, label: "Software Architecture" },
  { id: 32, label: "Object-Oriented Programming" },
  { id: 33, label: "Functional Programming" },
  { id: 34, label: "Database Design" },
  { id: 35, label: "SQL" },
  { id: 36, label: "NoSQL Databases" },
  { id: 37, label: "Redis" },
  { id: 38, label: "PostgreSQL" },
  { id: 39, label: "MySQL" },
  { id: 40, label: "MongoDB" },
  { id: 41, label: "AWS Cloud Services" },
  { id: 42, label: "Azure Cloud" },
  { id: 43, label: "Google Cloud Platform" },
  { id: 44, label: "Terraform" },
  { id: 45, label: "Linux Administration" },
  { id: 46, label: "Bash Scripting" },
  { id: 47, label: "Webpack" },
  { id: 48, label: "Performance Optimization" },
  { id: 49, label: "Security Best Practices" },
  { id: 50, label: "WebSocket Development" },
  { id: 51, label: "Flutter Development" },
  { id: 52, label: "React Native" },
  { id: 53, label: "Electron.js" },
  { id: 54, label: "WebAssembly" },
  { id: 55, label: "gRPC" },
  { id: 56, label: "Apache Kafka" },
  { id: 57, label: "RabbitMQ" },
  { id: 58, label: "Nginx Configuration" },
  { id: 59, label: "Load Balancing" },
  { id: 60, label: "OAuth / OpenID Connect" },
  { id: 61, label: "Elasticsearch" },
  { id: 62, label: "Serverless Architecture" },
  { id: 63, label: "Lambda Functions" },
  { id: 64, label: "Next.js" },
  { id: 65, label: "Nuxt.js" },
  { id: 66, label: "Svelte" },
  { id: 67, label: "FastAPI" },
  { id: 68, label: "Laravel" },
  { id: 69, label: "ASP.NET Core" },
  { id: 70, label: "Scala" },
  { id: 71, label: "Dart Programming" },
  { id: 72, label: "MATLAB" },
  { id: 73, label: "Blockchain Development" },
  { id: 74, label: "Smart Contracts (Solidity)" },
  { id: 75, label: "DevSecOps" },
  { id: 76, label: "Site Reliability Engineering" },
  { id: 77, label: "Chaos Engineering" },
  { id: 78, label: "Machine Learning" },
  { id: 79, label: "Deep Learning" },
  { id: 80, label: "Natural Language Processing" },
  { id: 81, label: "Computer Vision" },
  { id: 82, label: "Data Analysis" },
  { id: 83, label: "Data Visualization" },
  { id: 84, label: "Statistical Modeling" },
  { id: 85, label: "TensorFlow" },
  { id: 86, label: "PyTorch" },
  { id: 87, label: "Scikit-learn" },
  { id: 88, label: "Pandas" },
  { id: 89, label: "NumPy" },
  { id: 90, label: "R Programming" },
  { id: 91, label: "Tableau" },
  { id: 92, label: "Power BI" },
  { id: 93, label: "Big Data (Hadoop/Spark)" },
  { id: 94, label: "Feature Engineering" },
  { id: 95, label: "Model Deployment" },
  { id: 96, label: "A/B Testing" },
  { id: 97, label: "Predictive Analytics" },
  { id: 98, label: "Time Series Analysis" },
  { id: 99, label: "Reinforcement Learning" },
  { id: 100, label: "Generative AI" },
  { id: 101, label: "LLM Fine-tuning" },
  { id: 102, label: "ETL Pipelines" },
  { id: 103, label: "Data Warehousing" },
  { id: 104, label: "dbt (Data Build Tool)" },
  { id: 105, label: "Snowflake" },
  { id: 106, label: "Apache Airflow" },
  { id: 107, label: "MLOps" },
  { id: 108, label: "Hugging Face" },
  { id: 109, label: "OpenAI API Integration" },
  { id: 110, label: "Prompt Engineering" },
  { id: 111, label: "Vector Databases" },
  { id: 112, label: "RAG Systems" },
  { id: 113, label: "Causal Inference" },
  { id: 114, label: "Bayesian Statistics" },
  { id: 115, label: "Graph Neural Networks" },
  { id: 116, label: "Recommender Systems" },
  { id: 117, label: "Anomaly Detection" },
  { id: 118, label: "Penetration Testing" },
  { id: 119, label: "Ethical Hacking" },
  { id: 120, label: "Network Security" },
  { id: 121, label: "Incident Response" },
  { id: 122, label: "Threat Intelligence" },
  { id: 123, label: "SIEM Management" },
  { id: 124, label: "Vulnerability Assessment" },
  { id: 125, label: "Identity & Access Management" },
  { id: 126, label: "Zero Trust Architecture" },
  { id: 127, label: "Firewall Configuration" },
  { id: 128, label: "Cryptography" },
  { id: 129, label: "SOC Operations" },
  { id: 130, label: "Malware Analysis" },
  { id: 131, label: "Digital Forensics" },
  { id: 132, label: "Cloud Security" },
  { id: 133, label: "Compliance (ISO 27001)" },
  { id: 134, label: "Risk Assessment" },
  { id: 135, label: "Security Auditing" },
  { id: 136, label: "DDoS Mitigation" },
  { id: 137, label: "PKI Management" },
  { id: 138, label: "Manual Testing" },
  { id: 139, label: "Automated Testing" },
  { id: 140, label: "Selenium" },
  { id: 141, label: "Cypress" },
  { id: 142, label: "Playwright" },
  { id: 143, label: "API Testing (Postman)" },
  { id: 144, label: "Load Testing (JMeter)" },
  { id: 145, label: "Performance Testing" },
  { id: 146, label: "Security Testing" },
  { id: 147, label: "Mobile App Testing" },
  { id: 148, label: "Bug Tracking" },
  { id: 149, label: "Test Case Design" },
  { id: 150, label: "Test Planning" },
  { id: 151, label: "Regression Testing" },
  { id: 152, label: "Exploratory Testing" },
  { id: 153, label: "Accessibility Testing" },
  { id: 154, label: "UAT Coordination" },
  { id: 155, label: "ISTQB Certification" },
  { id: 156, label: "Appium" },
  { id: 157, label: "Cucumber BDD" },
  { id: 158, label: "AWS Lambda" },
  { id: 159, label: "AWS S3" },
  { id: 160, label: "AWS EC2" },
  { id: 161, label: "AWS RDS" },
  { id: 162, label: "Azure DevOps" },
  { id: 163, label: "GCP BigQuery" },
  { id: 164, label: "Infrastructure as Code" },
  { id: 165, label: "Ansible" },
  { id: 166, label: "Helm Charts" },
  { id: 167, label: "GitOps" },
  { id: 168, label: "Prometheus & Grafana" },
  { id: 169, label: "ELK Stack" },
  { id: 170, label: "Service Mesh (Istio)" },
  { id: 171, label: "Cost Optimization (Cloud)" },
  { id: 172, label: "Multi-cloud Strategy" },
  { id: 173, label: "Product Roadmapping" },
  { id: 174, label: "User Story Writing" },
  { id: 175, label: "Market Research" },
  { id: 176, label: "Competitive Analysis" },
  { id: 177, label: "Product Analytics" },
  { id: 178, label: "Stakeholder Management" },
  { id: 179, label: "Go-to-Market Strategy" },
  { id: 180, label: "Prioritization Frameworks" },
  { id: 181, label: "OKR Setting" },
  { id: 182, label: "Customer Discovery" },
  { id: 183, label: "Wireframing" },
  { id: 184, label: "Product-Led Growth" },
  { id: 185, label: "Agile/Scrum" },
  { id: 186, label: "Sprint Planning" },
  { id: 187, label: "Backlog Grooming" },
  { id: 188, label: "Feature Specification" },
  { id: 189, label: "KPI Tracking" },
  { id: 190, label: "User Feedback Analysis" },
  { id: 191, label: "Pricing Strategy" },
  { id: 192, label: "Product Lifecycle Management" },
  { id: 193, label: "User Interface Design" },
  { id: 194, label: "User Experience Research" },
  { id: 195, label: "Figma" },
  { id: 196, label: "Adobe XD" },
  { id: 197, label: "Sketch" },
  { id: 198, label: "Prototyping" },
  { id: 199, label: "Usability Testing" },
  { id: 200, label: "Design Systems" },
  { id: 201, label: "Information Architecture" },
  { id: 202, label: "Interaction Design" },
  { id: 203, label: "Motion Design" },
  { id: 204, label: "Accessibility Design (WCAG)" },
  { id: 205, label: "Design Thinking" },
  { id: 206, label: "User Journey Mapping" },
  { id: 207, label: "Persona Creation" },
  { id: 208, label: "A/B Testing (Design)" },
  { id: 209, label: "Responsive Design" },
  { id: 210, label: "Typography" },
  { id: 211, label: "Color Theory" },
  { id: 212, label: "InVision" },
  { id: 213, label: "Financial Modeling" },
  { id: 214, label: "Budgeting & Forecasting" },
  { id: 215, label: "Financial Statement Analysis" },
  { id: 216, label: "Management Accounting" },
  { id: 217, label: "Tax Planning" },
  { id: 218, label: "Auditing" },
  { id: 219, label: "Cash Flow Management" },
  { id: 220, label: "Accounts Payable" },
  { id: 221, label: "Accounts Receivable" },
  { id: 222, label: "Payroll Processing" },
  { id: 223, label: "IFRS/GAAP Compliance" },
  { id: 224, label: "Investment Analysis" },
  { id: 225, label: "Risk Management" },
  { id: 226, label: "Valuation" },
  { id: 227, label: "Cost Accounting" },
  { id: 228, label: "Revenue Recognition" },
  { id: 229, label: "Treasury Management" },
  { id: 230, label: "Mergers & Acquisitions" },
  { id: 231, label: "Financial Reporting" },
  { id: 232, label: "ERP Systems (SAP/Oracle)" },
  { id: 233, label: "QuickBooks" },
  { id: 234, label: "Excel Financial Analysis" },
  { id: 235, label: "Derivatives & Hedging" },
  { id: 236, label: "Credit Analysis" },
  { id: 237, label: "Portfolio Management" },
  { id: 238, label: "Blockchain in Finance" },
  { id: 239, label: "ESG Reporting" },
  { id: 240, label: "Cryptocurrency Analysis" },
  { id: 241, label: "Actuarial Analysis" },
  { id: 242, label: "Equity Research" },
  { id: 243, label: "Talent Acquisition" },
  { id: 244, label: "Employee Onboarding" },
  { id: 245, label: "Performance Management" },
  { id: 246, label: "Learning & Development" },
  { id: 247, label: "HR Policy Development" },
  { id: 248, label: "Compensation & Benefits" },
  { id: 249, label: "Employee Relations" },
  { id: 250, label: "Workforce Planning" },
  { id: 251, label: "HRIS Management" },
  { id: 252, label: "Diversity & Inclusion" },
  { id: 253, label: "Succession Planning" },
  { id: 254, label: "Labour Law Compliance" },
  { id: 255, label: "Payroll Management" },
  { id: 256, label: "Organizational Development" },
  { id: 257, label: "Employee Engagement" },
  { id: 258, label: "HR Analytics" },
  { id: 259, label: "Job Evaluation" },
  { id: 260, label: "Conflict Resolution" },
  { id: 261, label: "Exit Interviews" },
  { id: 262, label: "Employer Branding" },
  { id: 263, label: "Remote Work Management" },
  { id: 264, label: "Culture Building" },
  { id: 265, label: "Psychometric Testing" },
  { id: 266, label: "Compensation Benchmarking" },
  { id: 267, label: "HR Automation" },
  { id: 268, label: "People Analytics" },
  { id: 269, label: "Mental Health at Work" },
  { id: 270, label: "Talent Retention Strategy" },
  { id: 271, label: "Competency Framework Design" },
  { id: 272, label: "HR Business Partnering" },
  { id: 273, label: "Digital Marketing" },
  { id: 274, label: "SEO/SEM" },
  { id: 275, label: "Content Marketing" },
  { id: 276, label: "Social Media Marketing" },
  { id: 277, label: "Email Marketing" },
  { id: 278, label: "Brand Management" },
  { id: 279, label: "Campaign Management" },
  { id: 280, label: "Google Ads" },
  { id: 281, label: "Meta Ads" },
  { id: 282, label: "Influencer Marketing" },
  { id: 283, label: "Marketing Analytics" },
  { id: 284, label: "Copywriting" },
  { id: 285, label: "Market Segmentation" },
  { id: 286, label: "CRM Marketing" },
  { id: 287, label: "Conversion Rate Optimization" },
  { id: 288, label: "Video Marketing" },
  { id: 289, label: "Affiliate Marketing" },
  { id: 290, label: "Public Relations" },
  { id: 291, label: "Event Marketing" },
  { id: 292, label: "Account-Based Marketing" },
  { id: 293, label: "Growth Hacking" },
  { id: 294, label: "Customer Retention" },
  { id: 295, label: "Marketing Automation" },
  { id: 296, label: "HubSpot" },
  { id: 297, label: "Salesforce Marketing Cloud" },
  { id: 298, label: "Performance Marketing" },
  { id: 299, label: "Programmatic Advertising" },
  { id: 300, label: "TikTok Marketing" },
  { id: 301, label: "LinkedIn Marketing" },
  { id: 302, label: "YouTube Marketing" },
  { id: 303, label: "Customer Lifetime Value (CLV)" },
  { id: 304, label: "Marketing Mix Modeling" },
  { id: 305, label: "Podcast Marketing" },
  { id: 306, label: "App Store Optimization (ASO)" },
  { id: 307, label: "Product Marketing" },
  { id: 308, label: "B2B Sales" },
  { id: 309, label: "B2C Sales" },
  { id: 310, label: "Lead Generation" },
  { id: 311, label: "Cold Calling" },
  { id: 312, label: "Sales Negotiation" },
  { id: 313, label: "CRM Management" },
  { id: 314, label: "Pipeline Management" },
  { id: 315, label: "Account Management" },
  { id: 316, label: "Solution Selling" },
  { id: 317, label: "Sales Forecasting" },
  { id: 318, label: "Customer Acquisition" },
  { id: 319, label: "Upselling & Cross-selling" },
  { id: 320, label: "SaaS Sales" },
  { id: 321, label: "Enterprise Sales" },
  { id: 322, label: "Sales Presentations" },
  { id: 323, label: "Closing Techniques" },
  { id: 324, label: "Territory Management" },
  { id: 325, label: "Channel Sales" },
  { id: 326, label: "Inside Sales" },
  { id: 327, label: "Salesforce CRM" },
  { id: 328, label: "Supply Chain Management" },
  { id: 329, label: "Inventory Management" },
  { id: 330, label: "Procurement" },
  { id: 331, label: "Vendor Management" },
  { id: 332, label: "Logistics Coordination" },
  { id: 333, label: "Warehouse Management" },
  { id: 334, label: "Demand Forecasting" },
  { id: 335, label: "Process Improvement" },
  { id: 336, label: "Lean Manufacturing" },
  { id: 337, label: "Six Sigma" },
  { id: 338, label: "ERP Systems" },
  { id: 339, label: "Quality Assurance" },
  { id: 340, label: "Order Fulfillment" },
  { id: 341, label: "Import/Export Compliance" },
  { id: 342, label: "Fleet Management" },
  { id: 343, label: "Production Planning" },
  { id: 344, label: "Contract Management" },
  { id: 345, label: "Cost Reduction" },
  { id: 346, label: "Risk Mitigation" },
  { id: 347, label: "Supplier Auditing" },
  { id: 348, label: "Patient Care" },
  { id: 349, label: "Clinical Assessment" },
  { id: 350, label: "Medical Documentation" },
  { id: 351, label: "Electronic Health Records (EHR)" },
  { id: 352, label: "Medication Administration" },
  { id: 353, label: "Infection Control" },
  { id: 354, label: "Surgical Assistance" },
  { id: 355, label: "Emergency Response" },
  { id: 356, label: "Patient Education" },
  { id: 357, label: "Diagnostic Imaging" },
  { id: 358, label: "Laboratory Testing" },
  { id: 359, label: "Physiotherapy" },
  { id: 360, label: "Mental Health Counseling" },
  { id: 361, label: "Telemedicine" },
  { id: 362, label: "Health Informatics" },
  { id: 363, label: "Medical Coding (ICD-10)" },
  { id: 364, label: "Pharmacy Management" },
  { id: 365, label: "Nutrition & Dietetics" },
  { id: 366, label: "Occupational Therapy" },
  { id: 367, label: "Public Health Promotion" },
  { id: 368, label: "Clinical Research" },
  { id: 369, label: "Healthcare Compliance (HIPAA)" },
  { id: 370, label: "Palliative Care" },
  { id: 371, label: "Pediatric Care" },
  { id: 372, label: "Geriatric Care" },
  { id: 373, label: "Radiology" },
  { id: 374, label: "Cardiology Support" },
  { id: 375, label: "Surgical Technology" },
  { id: 376, label: "Speech Therapy" },
  { id: 377, label: "Respiratory Therapy" },
  { id: 378, label: "Medical Device Operation" },
  { id: 379, label: "Epidemiology" },
  { id: 380, label: "Health Policy" },
  { id: 381, label: "Biomedical Research" },
  { id: 382, label: "Nursing Management" },
  { id: 383, label: "Psychiatric Care" },
  { id: 384, label: "Wound Care" },
  { id: 385, label: "Rehabilitation Services" },
  { id: 386, label: "Curriculum Development" },
  { id: 387, label: "Lesson Planning" },
  { id: 388, label: "Classroom Management" },
  { id: 389, label: "E-Learning Development" },
  { id: 390, label: "Student Assessment" },
  { id: 391, label: "Instructional Design" },
  { id: 392, label: "Special Education" },
  { id: 393, label: "Early Childhood Education" },
  { id: 394, label: "Adult Learning (Andragogy)" },
  { id: 395, label: "Educational Technology" },
  { id: 396, label: "Learning Management Systems" },
  { id: 397, label: "Tutoring" },
  { id: 398, label: "Academic Research" },
  { id: 399, label: "Grant Writing" },
  { id: 400, label: "Student Counseling" },
  { id: 401, label: "STEM Education" },
  { id: 402, label: "Language Teaching (TEFL/TESOL)" },
  { id: 403, label: "School Administration" },
  { id: 404, label: "Educational Policy" },
  { id: 405, label: "Blended Learning" },
  { id: 406, label: "Contract Drafting" },
  { id: 407, label: "Legal Research" },
  { id: 408, label: "Corporate Law" },
  { id: 409, label: "Intellectual Property Law" },
  { id: 410, label: "Employment Law" },
  { id: 411, label: "Litigation Support" },
  { id: 412, label: "Regulatory Compliance" },
  { id: 413, label: "Mergers & Acquisitions (Legal)" },
  { id: 414, label: "Data Privacy Law (GDPR)" },
  { id: 415, label: "Real Estate Law" },
  { id: 416, label: "Tax Law" },
  { id: 417, label: "Criminal Law" },
  { id: 418, label: "Legal Documentation" },
  { id: 419, label: "Arbitration & Mediation" },
  { id: 420, label: "Legal Project Management" },
  { id: 421, label: "Due Diligence" },
  { id: 422, label: "Patent Filing" },
  { id: 423, label: "Trademark Registration" },
  { id: 424, label: "Legal Risk Assessment" },
  { id: 425, label: "Court Representation" },
  { id: 426, label: "AutoCAD" },
  { id: 427, label: "SolidWorks" },
  { id: 428, label: "Structural Analysis" },
  { id: 429, label: "Finite Element Analysis (FEA)" },
  { id: 430, label: "Civil Engineering Design" },
  { id: 431, label: "Electrical Circuit Design" },
  { id: 432, label: "PLC Programming" },
  { id: 433, label: "SCADA Systems" },
  { id: 434, label: "Mechanical Design" },
  { id: 435, label: "HVAC Systems" },
  { id: 436, label: "Project Engineering" },
  { id: 437, label: "Environmental Engineering" },
  { id: 438, label: "Geotechnical Engineering" },
  { id: 439, label: "Construction Management" },
  { id: 440, label: "Building Information Modeling (BIM)" },
  { id: 441, label: "PCB Design" },
  { id: 442, label: "Embedded Systems" },
  { id: 443, label: "Robotics" },
  { id: 444, label: "Thermodynamics" },
  { id: 445, label: "Hydraulics & Pneumatics" },
  { id: 446, label: "Quality Control" },
  { id: 447, label: "NDT Testing" },
  { id: 448, label: "Material Science" },
  { id: 449, label: "3D Printing/Additive Manufacturing" },
  { id: 450, label: "Energy Auditing" },
  { id: 451, label: "Project Planning" },
  { id: 452, label: "Risk Management (PM)" },
  { id: 453, label: "Stakeholder Communication" },
  { id: 454, label: "Budget Management" },
  { id: 455, label: "MS Project" },
  { id: 456, label: "Jira" },
  { id: 457, label: "Asana" },
  { id: 458, label: "PMP Methodology" },
  { id: 459, label: "PRINCE2" },
  { id: 460, label: "Agile Project Management" },
  { id: 461, label: "Waterfall Methodology" },
  { id: 462, label: "Resource Allocation" },
  { id: 463, label: "Change Management" },
  { id: 464, label: "Gantt Charts" },
  { id: 465, label: "Milestone Tracking" },
  { id: 466, label: "Vendor Coordination" },
  { id: 467, label: "Quality Management" },
  { id: 468, label: "Scope Management" },
  { id: 469, label: "Lessons Learned" },
  { id: 470, label: "Program Management" },
  { id: 471, label: "Customer Support" },
  { id: 472, label: "Complaint Handling" },
  { id: 473, label: "Help Desk Management" },
  { id: 474, label: "Live Chat Support" },
  { id: 475, label: "Call Center Operations" },
  { id: 476, label: "Customer Retention (Service)" },
  { id: 477, label: "Ticketing Systems (Zendesk)" },
  { id: 478, label: "SLA Management" },
  { id: 479, label: "Customer Satisfaction (CSAT)" },
  { id: 480, label: "Net Promoter Score (NPS)" },
  { id: 481, label: "Upselling in Service" },
  { id: 482, label: "Escalation Management" },
  { id: 483, label: "Multilingual Support" },
  { id: 484, label: "Technical Support" },
  { id: 485, label: "Knowledge Base Management" },
  { id: 486, label: "Property Valuation" },
  { id: 487, label: "Real Estate Sales" },
  { id: 488, label: "Property Management" },
  { id: 489, label: "Lease Negotiation" },
  { id: 490, label: "Real Estate Investment Analysis" },
  { id: 491, label: "Commercial Real Estate" },
  { id: 492, label: "Residential Real Estate" },
  { id: 493, label: "Market Analysis" },
  { id: 494, label: "Property Development" },
  { id: 495, label: "Facility Management" },
  { id: 496, label: "Mortgage Advising" },
  { id: 497, label: "Title & Escrow" },
  { id: 498, label: "Tenant Relations" },
  { id: 499, label: "Building Inspection" },
  { id: 500, label: "Hotel Management" },
  { id: 501, label: "Front Desk Operations" },
  { id: 502, label: "Food & Beverage Management" },
  { id: 503, label: "Event Planning" },
  { id: 504, label: "Tour Operations" },
  { id: 505, label: "Revenue Management" },
  { id: 506, label: "Guest Relations" },
  { id: 507, label: "Housekeeping Management" },
  { id: 508, label: "Catering Management" },
  { id: 509, label: "Travel Planning" },
  { id: 510, label: "Concierge Services" },
  { id: 511, label: "Restaurant Management" },
  { id: 512, label: "Spa & Wellness Management" },
  { id: 513, label: "Tourism Marketing" },
  { id: 514, label: "POS Systems" },
  { id: 515, label: "Food Safety & Hygiene" },
  { id: 516, label: "Menu Planning" },
  { id: 517, label: "Banquet Operations" },
  { id: 518, label: "Resort Management" },
  { id: 519, label: "Airline Operations" },
  { id: 520, label: "Retail Sales" },
  { id: 521, label: "Inventory Control" },
  { id: 522, label: "Visual Merchandising" },
  { id: 523, label: "Store Management" },
  { id: 524, label: "Point of Sale (POS) Systems" },
  { id: 525, label: "Loss Prevention" },
  { id: 526, label: "Category Management" },
  { id: 527, label: "E-commerce Management" },
  { id: 528, label: "Supply Chain (Retail)" },
  { id: 529, label: "Customer Loyalty Programs" },
  { id: 530, label: "Planogramming" },
  { id: 531, label: "Retail Analytics" },
  { id: 532, label: "Product Sourcing" },
  { id: 533, label: "Promotional Planning" },
  { id: 534, label: "Omnichannel Retail" },
  { id: 535, label: "Production Management" },
  { id: 536, label: "Quality Control (Manufacturing)" },
  { id: 537, label: "Lean Manufacturing (Mfg)" },
  { id: 538, label: "Six Sigma (Manufacturing)" },
  { id: 539, label: "Equipment Maintenance" },
  { id: 540, label: "Safety Management (EHS)" },
  { id: 541, label: "CNC Machining" },
  { id: 542, label: "Assembly Line Management" },
  { id: 543, label: "Welding" },
  { id: 544, label: "ISO 9001 Compliance" },
  { id: 545, label: "Material Requirements Planning (MRP)" },
  { id: 546, label: "Tooling & Fixture Design" },
  { id: 547, label: "Statistical Process Control" },
  { id: 548, label: "Capacity Planning" },
  { id: 549, label: "Root Cause Analysis" },
  { id: 550, label: "Journalism" },
  { id: 551, label: "Content Writing" },
  { id: 552, label: "Video Production" },
  { id: 553, label: "Podcast Production" },
  { id: 554, label: "Photography" },
  { id: 555, label: "Graphic Design" },
  { id: 556, label: "Adobe Photoshop" },
  { id: 557, label: "Adobe Illustrator" },
  { id: 558, label: "Adobe Premiere Pro" },
  { id: 559, label: "After Effects" },
  { id: 560, label: "Social Media Content Creation" },
  { id: 561, label: "Scriptwriting" },
  { id: 562, label: "Broadcast Journalism" },
  { id: 563, label: "Media Planning" },
  { id: 564, label: "Press Release Writing" },
  { id: 565, label: "Crisis Communication" },
  { id: 566, label: "Proofreading & Editing" },
  { id: 567, label: "Translation" },
  { id: 568, label: "Subtitling" },
  { id: 569, label: "Brand Storytelling" },
  { id: 570, label: "Architectural Design" },
  { id: 571, label: "Urban Planning" },
  { id: 572, label: "Interior Design" },
  { id: 573, label: "Landscape Architecture" },
  { id: 574, label: "Revit" },
  { id: 575, label: "SketchUp" },
  { id: 576, label: "3D Rendering" },
  { id: 577, label: "Space Planning" },
  { id: 578, label: "Sustainable Design" },
  { id: 579, label: "Building Regulations Compliance" },
  { id: 580, label: "Site Analysis" },
  { id: 581, label: "Construction Documentation" },
  { id: 582, label: "Project Specification Writing" },
  { id: 583, label: "Heritage Conservation" },
  { id: 584, label: "Lighting Design" },
  { id: 585, label: "Grant Writing (Non-Profit)" },
  { id: 586, label: "Community Outreach" },
  { id: 587, label: "Fundraising" },
  { id: 588, label: "Volunteer Management" },
  { id: 589, label: "Program Evaluation" },
  { id: 590, label: "Case Management" },
  { id: 591, label: "Social Work" },
  { id: 592, label: "NGO Management" },
  { id: 593, label: "Advocacy & Lobbying" },
  { id: 594, label: "Impact Measurement" },
  { id: 595, label: "Donor Relations" },
  { id: 596, label: "Crisis Intervention" },
  { id: 597, label: "Community Development" },
  { id: 598, label: "Child Protection" },
  { id: 599, label: "Humanitarian Aid Coordination" },
  { id: 600, label: "Fleet Management (Transport)" },
  { id: 601, label: "Route Optimization" },
  { id: 602, label: "Freight Management" },
  { id: 603, label: "Customs Brokerage" },
  { id: 604, label: "Last-Mile Delivery" },
  { id: 605, label: "Cold Chain Logistics" },
  { id: 606, label: "Shipping & Receiving" },
  { id: 607, label: "Hazmat Handling" },
  { id: 608, label: "Transportation Planning" },
  { id: 609, label: "Driver Management" },
  { id: 610, label: "Cargo Management" },
  { id: 611, label: "Logistics Software (SAP TM)" },
  { id: 612, label: "Port Operations" },
  { id: 613, label: "Air Freight Management" },
  { id: 614, label: "Sea Freight Management" },
  { id: 615, label: "Power Systems Engineering" },
  { id: 616, label: "Renewable Energy" },
  { id: 617, label: "Solar Energy Systems" },
  { id: 618, label: "Wind Energy" },
  { id: 619, label: "Energy Auditing (Utilities)" },
  { id: 620, label: "Grid Management" },
  { id: 621, label: "Oil & Gas Operations" },
  { id: 622, label: "Pipeline Engineering" },
  { id: 623, label: "Energy Policy" },
  { id: 624, label: "SCADA (Utilities)" },
  { id: 625, label: "Utility Billing" },
  { id: 626, label: "Environmental Compliance" },
  { id: 627, label: "Water Treatment" },
  { id: 628, label: "Gas Distribution" },
  { id: 629, label: "Nuclear Plant Operations" },
  { id: 630, label: "Crop Management" },
  { id: 631, label: "Soil Science" },
  { id: 632, label: "Irrigation Management" },
  { id: 633, label: "Livestock Management" },
  { id: 634, label: "Agri-Business Management" },
  { id: 635, label: "Precision Agriculture" },
  { id: 636, label: "Pest & Disease Control" },
  { id: 637, label: "Agricultural Machinery Operation" },
  { id: 638, label: "Food Safety Compliance" },
  { id: 639, label: "Hydroponics" },
  { id: 640, label: "Greenhouse Management" },
  { id: 641, label: "Agricultural Extension" },
  { id: 642, label: "Seed Technology" },
  { id: 643, label: "Agricultural Supply Chain" },
  { id: 644, label: "Farm Financial Management" },
  { id: 645, label: "Retail Banking" },
  { id: 646, label: "Corporate Banking" },
  { id: 647, label: "Trade Finance" },
  { id: 648, label: "Credit Underwriting" },
  { id: 649, label: "KYC/AML Compliance" },
  { id: 650, label: "Wealth Management" },
  { id: 651, label: "Investment Banking" },
  { id: 652, label: "Treasury Operations" },
  { id: 653, label: "Loan Processing" },
  { id: 654, label: "Financial Risk Management" },
  { id: 655, label: "Capital Markets" },
  { id: 656, label: "Foreign Exchange (FX)" },
  { id: 657, label: "Private Equity" },
  { id: 658, label: "Digital Banking" },
  { id: 659, label: "Fintech Solutions" },
  { id: 660, label: "Business Model Development" },
  { id: 661, label: "Startup Strategy" },
  { id: 662, label: "Venture Capital" },
  { id: 663, label: "Business Development" },
  { id: 664, label: "Strategic Partnerships" },
  { id: 665, label: "Corporate Strategy" },
  { id: 666, label: "Pitch Deck Creation" },
  { id: 667, label: "Market Entry Strategy" },
  { id: 668, label: "Competitive Intelligence" },
  { id: 669, label: "Business Planning" },
  { id: 670, label: "Innovation Management" },
  { id: 671, label: "Design Sprint Facilitation" },
  { id: 672, label: "Digital Transformation" },
  { id: 673, label: "P&L Management" },
  { id: 674, label: "Growth Strategy" },
  { id: 675, label: "Turnaround Management" },
  { id: 676, label: "Board Reporting" },
  { id: 677, label: "Environmental Impact Assessment" },
  { id: 678, label: "Carbon Footprint Analysis" },
  { id: 679, label: "ESG Strategy" },
  { id: 680, label: "Sustainability Reporting" },
  { id: 681, label: "Climate Risk Analysis" },
  { id: 682, label: "Waste Management" },
  { id: 683, label: "Circular Economy" },
  { id: 684, label: "Green Building Certification" },
  { id: 685, label: "Biodiversity Management" },
  { id: 686, label: "Water Resource Management" },
  { id: 687, label: "Environmental Auditing" },
  { id: 688, label: "Carbon Trading" },
  { id: 689, label: "Renewable Energy Policy" },
  { id: 690, label: "Life Cycle Assessment (LCA)" },
  { id: 691, label: "Corporate Social Responsibility (CSR)" },
  { id: 692, label: "Illustration" },
  { id: 693, label: "Animation (2D/3D)" },
  { id: 694, label: "Game Design" },
  { id: 695, label: "Music Production" },
  { id: 696, label: "Sound Design" },
  { id: 697, label: "Storyboarding" },
  { id: 698, label: "Art Direction" },
  { id: 699, label: "Fashion Design" },
  { id: 700, label: "Textile Design" },
  { id: 701, label: "Industrial Design" },
  { id: 702, label: "Creative Writing" },
  { id: 703, label: "Blender 3D" },
  { id: 704, label: "Cinema 4D" },
  { id: 705, label: "Unity Game Engine" },
  { id: 706, label: "Unreal Engine" },
  { id: 707, label: "Underwriting" },
  { id: 708, label: "Claims Management" },
  { id: 709, label: "Actuarial Science" },
  { id: 710, label: "Insurance Sales" },
  { id: 711, label: "Reinsurance" },
  { id: 712, label: "Loss Adjustment" },
  { id: 713, label: "Policy Administration" },
  { id: 714, label: "Insurance Compliance" },
  { id: 715, label: "Risk Engineering" },
  { id: 716, label: "Health Insurance Management" },
  { id: 717, label: "Life Insurance Planning" },
  { id: 718, label: "InsurTech" },
  { id: 719, label: "Catastrophe Modeling" },
  { id: 720, label: "Broker Relations" },
  { id: 721, label: "Insurance Analytics" },
  { id: 722, label: "Policy Development" },
  { id: 723, label: "Public Administration" },
  { id: 724, label: "Government Procurement" },
  { id: 725, label: "Regulatory Affairs" },
  { id: 726, label: "Urban Development Planning" },
  { id: 727, label: "Public Finance Management" },
  { id: 728, label: "E-Government Services" },
  { id: 729, label: "International Relations" },
  { id: 730, label: "Diplomatic Protocol" },
  { id: 731, label: "Electoral Administration" },
  { id: 732, label: "Census & Statistics" },
  { id: 733, label: "Immigration Services" },
  { id: 734, label: "Judicial Administration" },
  { id: 735, label: "Emergency Management" },
  { id: 736, label: "Network Engineering" },
  { id: 737, label: "5G Technology" },
  { id: 738, label: "VoIP Systems" },
  { id: 739, label: "Fiber Optic Installation" },
  { id: 740, label: "RF Engineering" },
  { id: 741, label: "Telecom Project Management" },
  { id: 742, label: "OSS/BSS Systems" },
  { id: 743, label: "Network Monitoring" },
  { id: 744, label: "Satellite Communications" },
  { id: 745, label: "Telecom Regulatory Compliance" },
  { id: 746, label: "Core Network Architecture" },
  { id: 747, label: "IoT Connectivity" },
  { id: 748, label: "Telecom Analytics" },
  { id: 749, label: "Customer Experience (Telco)" },
  { id: 750, label: "Spectrum Management" },
  { id: 751, label: "Leadership" },
  { id: 752, label: "Communication" },
  { id: 753, label: "Critical Thinking" },
  { id: 754, label: "Problem Solving" },
  { id: 755, label: "Team Collaboration" },
  { id: 756, label: "Time Management" },
  { id: 757, label: "Adaptability" },
  { id: 758, label: "Emotional Intelligence" },
  { id: 759, label: "Negotiation" },
  { id: 760, label: "Presentation Skills" },
  { id: 761, label: "Decision Making" },
  { id: 762, label: "Mentoring & Coaching" },
  { id: 763, label: "Cross-functional Collaboration" },
  { id: 764, label: "Business Writing" },
  { id: 765, label: "Data-Driven Decision Making" },
  { id: 766, label: "Strategic Thinking" },
  { id: 767, label: "Creativity & Innovation" },
  { id: 768, label: "Multitasking" },
  { id: 769, label: "Customer Focus" },
  { id: 770, label: "Attention to Detail" },
  { id: 771, label: "Active Listening" },
  { id: 772, label: "Stakeholder Engagement" },
  { id: 773, label: "Intercultural Communication" },
  { id: 774, label: "Resilience" },
  { id: 775, label: "Accountability" },
  { id: 776, label: "Conflict Management" },
  { id: 777, label: "Growth Mindset" },
  { id: 778, label: "Executive Presence" },
  { id: 779, label: "Facilitation" },
  { id: 780, label: "Networking" },
  { id: 781, label: "Montessori Teaching" },
  { id: 782, label: "Online Course Design" },
  { id: 783, label: "Student Motivation Techniques" },
  { id: 784, label: "Peer Learning Facilitation" },
  { id: 785, label: "Academic Writing" },
  { id: 786, label: "Environmental Law" },
  { id: 787, label: "Banking Law" },
  { id: 788, label: "Competition Law" },
  { id: 789, label: "International Trade Law" },
  { id: 790, label: "Family Law" },
  { id: 791, label: "Anesthesia Assistance" },
  { id: 792, label: "Infection Epidemiology" },
  { id: 793, label: "Clinical Governance" },
  { id: 794, label: "Neonatal Care" },
  { id: 795, label: "Dermatology Assistance" },
  { id: 796, label: "Internal Audit" },
  { id: 797, label: "Xero Accounting" },
  { id: 798, label: "Transfer Pricing" },
  { id: 799, label: "Forensic Accounting" },
  { id: 800, label: "Government Accounting" },
  { id: 801, label: "Fire Protection Engineering" },
  { id: 802, label: "Acoustical Engineering" },
  { id: 803, label: "Corrosion Engineering" },
  { id: 804, label: "Reliability Engineering" },
  { id: 805, label: "Offshore Engineering" },
  { id: 806, label: "Water Supply Engineering" },
  { id: 807, label: "Transportation Engineering" },
  { id: 808, label: "Pavement Engineering" },
  { id: 809, label: "Biomedical Engineering" },
  { id: 810, label: "Systems Engineering" },
  { id: 811, label: "Petroleum Engineering" },
  { id: 812, label: "Aerospace Engineering" },
  { id: 813, label: "Marine Engineering" },
  { id: 814, label: "Mining Engineering" },
  { id: 815, label: "Chemical Engineering" },
  { id: 816, label: "Nuclear Engineering" },
  { id: 817, label: "Control Systems Engineering" },
  { id: 818, label: "Instrumentation Engineering" },
  { id: 819, label: "Telecommunications Engineering" },
  { id: 820, label: "Power Electronics" },
  { id: 821, label: "AI Ethics" },
  { id: 822, label: "Data Governance" },
  { id: 823, label: "Knowledge Graphs" },
  { id: 824, label: "Edge Computing" },
  { id: 825, label: "Quantum Computing" },
  { id: 826, label: "AR/VR Development" },
  { id: 827, label: "Digital Twin" },
  { id: 828, label: "Computer-Aided Design (CAD)" },
  { id: 829, label: "Building Automation Systems" },
  { id: 830, label: "Renewable Energy Finance" },
  { id: 831, label: "Social Impact Assessment" },
  { id: 832, label: "Stakeholder Mapping" },
  { id: 833, label: "Governance Frameworks" },
  { id: 834, label: "Anti-Money Laundering" },
  { id: 835, label: "Sanctions Compliance" },
  { id: 836, label: "Fraud Detection" },
  { id: 837, label: "Payment Systems" },
  { id: 838, label: "Central Banking Operations" },
  { id: 839, label: "Microfinance" },
  { id: 840, label: "Agricultural Finance" },
  { id: 841, label: "Trade Compliance" },
  { id: 842, label: "Customs Valuation" },
  { id: 843, label: "International Logistics" },
  { id: 844, label: "Warehouse Automation" },
  { id: 845, label: "Supply Chain Risk Management" },
  { id: 846, label: "Demand Planning" },
  { id: 847, label: "Retail Buying" },
  { id: 848, label: "Fashion Merchandising" },
  { id: 849, label: "Luxury Brand Management" },
  { id: 850, label: "Franchise Management" },
  { id: 851, label: "Medical Transcription" },
  { id: 852, label: "Health Economics" },
  { id: 853, label: "Clinical Trials Management" },
  { id: 854, label: "Pharmacovigilance" },
  { id: 855, label: "Medical Writing" },
  { id: 856, label: "Regulatory Affairs (Pharma)" },
  { id: 857, label: "Drug Safety" },
  { id: 858, label: "Good Manufacturing Practice (GMP)" },
  { id: 859, label: "Biostatistics" },
  { id: 860, label: "Medical Affairs" },
  { id: 861, label: "Change Leadership" },
  { id: 862, label: "Executive Coaching" },
  { id: 863, label: "Board Governance" },
  { id: 864, label: "Crisis Management" },
  { id: 865, label: "Organizational Design" },
  { id: 866, label: "Mergers Integration" },
  { id: 867, label: "Cultural Transformation" },
  { id: 868, label: "Business Process Reengineering" },
  { id: 869, label: "Operational Excellence" },
  { id: 870, label: "Continuous Improvement" },
  { id: 871, label: "Technical Writing" },
  { id: 872, label: "UX Writing" },
  { id: 873, label: "SEO Content Writing" },
  { id: 874, label: "Grant Proposal Writing" },
  { id: 875, label: "Speech Writing" },
  { id: 876, label: "Report Writing" },
  { id: 877, label: "Research Paper Writing" },
  { id: 878, label: "Blog Writing" },
  { id: 879, label: "White Paper Writing" },
  { id: 880, label: "Newsletter Writing" },
  { id: 881, label: "iOS Development" },
  { id: 882, label: "Android Development" },
  { id: 883, label: "Cross-Platform Development" },
  { id: 884, label: "Mobile UI/UX Design" },
  { id: 885, label: "App Performance Optimization" },
  { id: 886, label: "Push Notification Systems" },
  { id: 887, label: "Mobile Security" },
  { id: 888, label: "App Store Publishing" },
  { id: 889, label: "Mobile Analytics" },
  { id: 890, label: "Progressive Web Apps (PWA)" },
  { id: 891, label: "Venture Capital Analysis" },
  { id: 892, label: "Angel Investing" },
  { id: 893, label: "Startup Fundraising" },
  { id: 894, label: "Cap Table Management" },
  { id: 895, label: "Term Sheet Negotiation" },
  { id: 896, label: "Due Diligence (VC)" },
  { id: 897, label: "Portfolio Company Support" },
  { id: 898, label: "Startup Valuation" },
  { id: 899, label: "Exit Strategy Planning" },
  { id: 900, label: "LP Relations" },
  { id: 901, label: "Sports Management" },
  { id: 902, label: "Athlete Development" },
  { id: 903, label: "Sports Analytics" },
  { id: 904, label: "Event Coordination (Sports)" },
  { id: 905, label: "Sports Marketing" },
  { id: 906, label: "Fitness Training" },
  { id: 907, label: "Sports Medicine" },
  { id: 908, label: "Team Coaching" },
  { id: 909, label: "Sports Psychology" },
  { id: 910, label: "Recreation Management" },
  { id: 911, label: "Import Documentation" },
  { id: 912, label: "Export Documentation" },
  { id: 913, label: "Letter of Credit" },
  { id: 914, label: "Incoterms" },
  { id: 915, label: "Tariff Classification" },
  { id: 916, label: "Free Trade Agreements" },
  { id: 917, label: "Export Controls" },
  { id: 918, label: "Customs Audit" },
  { id: 919, label: "Trade Documentation" },
  { id: 920, label: "International Payments" },
  { id: 921, label: "Drone Operations" },
  { id: 922, label: "GIS Mapping" },
  { id: 923, label: "Remote Sensing" },
  { id: 924, label: "Surveying" },
  { id: 925, label: "Geospatial Analysis" },
  { id: 926, label: "Cartography" },
  { id: 927, label: "GPS Technology" },
  { id: 928, label: "Satellite Imagery Analysis" },
  { id: 929, label: "Topographic Mapping" },
  { id: 930, label: "LiDAR" },
  { id: 931, label: "Food Science" },
  { id: 932, label: "Food Processing" },
  { id: 933, label: "Food Quality Assurance" },
  { id: 934, label: "HACCP" },
  { id: 935, label: "Food Packaging" },
  { id: 936, label: "Sensory Evaluation" },
  { id: 937, label: "Food Microbiology" },
  { id: 938, label: "Bakery Technology" },
  { id: 939, label: "Beverage Technology" },
  { id: 940, label: "Dairy Technology" },
  { id: 941, label: "Textile Engineering" },
  { id: 942, label: "Garment Manufacturing" },
  { id: 943, label: "Pattern Making" },
  { id: 944, label: "Dyeing & Finishing" },
  { id: 945, label: "Quality Inspection (Textiles)" },
  { id: 946, label: "Fabric Sourcing" },
  { id: 947, label: "Apparel Production Planning" },
  { id: 948, label: "Textile Testing" },
  { id: 949, label: "Fashion Technology" },
  { id: 950, label: "Sustainable Fashion" },
  { id: 951, label: "Library Science" },
  { id: 952, label: "Information Management" },
  { id: 953, label: "Digital Archiving" },
  { id: 954, label: "Records Management" },
  { id: 955, label: "Cataloging & Classification" },
  { id: 956, label: "Research Data Management" },
  { id: 957, label: "Collection Development" },
  { id: 958, label: "Reference Services" },
  { id: 959, label: "Metadata Management" },
  { id: 960, label: "Digital Preservation" },
  { id: 961, label: "Veterinary Medicine" },
  { id: 962, label: "Animal Husbandry" },
  { id: 963, label: "Animal Nutrition" },
  { id: 964, label: "Poultry Science" },
  { id: 965, label: "Aquaculture" },
  { id: 966, label: "Wildlife Management" },
  { id: 967, label: "Animal Welfare" },
  { id: 968, label: "Veterinary Surgery" },
  { id: 969, label: "Livestock Genetics" },
  { id: 970, label: "Equine Management" },
  { id: 971, label: "Conflict Resolution (Intl)" },
  { id: 972, label: "Peacekeeping Operations" },
  { id: 973, label: "Intelligence Analysis" },
  { id: 974, label: "Border Security" },
  { id: 975, label: "Counter-Terrorism" },
  { id: 976, label: "Defense Logistics" },
  { id: 977, label: "Military Strategy" },
  { id: 978, label: "Security Consulting" },
  { id: 979, label: "Maritime Security" },
  { id: 980, label: "Aviation Security" },
  { id: 981, label: "Cognitive Behavioral Therapy" },
  { id: 982, label: "Play Therapy" },
  { id: 983, label: "Family Therapy" },
  { id: 984, label: "Grief Counseling" },
  { id: 985, label: "Addiction Counseling" },
  { id: 986, label: "Career Counseling" },
  { id: 987, label: "Rehabilitation Counseling" },
  { id: 988, label: "Art Therapy" },
  { id: 989, label: "Music Therapy" },
  { id: 990, label: "Mindfulness-Based Therapy" },
  { id: 991, label: "Blockchain Architecture" },
  { id: 992, label: "Token Economics" },
  { id: 993, label: "DeFi Protocols" },
  { id: 994, label: "NFT Development" },
  { id: 995, label: "Cryptocurrency Trading" },
  { id: 996, label: "Web3 Development" },
  { id: 997, label: "DAOs" },
  { id: 998, label: "Cross-Chain Interoperability" },
  { id: 999, label: "Consensus Mechanisms" },
  { id: 1000, label: "Zero-Knowledge Proofs" },
  { id: 1001, label: "Systems Thinking" }
];
