export enum MyRequestModalEnums {
  LEAVE_TYPE_SELECTION = "LEAVE_TYPE_SELECTION",
  APPLY_LEAVE = "APPLY_LEAVE",
  TEAM_AVAILABILITY = "TEAM_AVAILABILITY",
  ADD_ATTACHMENT = "ADD_ATTACHMENT",
  MARK_OUT_OF_OFFICE = "MARK_OUT_OF_OFFICE",
  NONE = "NONE"
}

export enum LeaveStatusEnums {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  CANCELLED = "CANCELLED",
  DENIED = "DENIED"
}

export enum ApplyLeaveToastEnums {
  APPLY_LEAVE_ERROR = "APPLY_LEAVE_ERROR",
  APPLY_LEAVE_SUCCESS = "APPLY_LEAVE_SUCCESS",
  LEAVE_ERROR_LEAVE_ENTITLEMENT_NOT_SUFFICIENT = "LEAVE_ERROR_LEAVE_ENTITLEMENT_NOT_SUFFICIENT",
  LEAVE_ERROR_LEAVE_ENTITLEMENT_NOT_APPLICABLE = "LEAVE_ERROR_LEAVE_ENTITLEMENT_NOT_APPLICABLE"
}

/** Backend message keys the policy apply flow maps to specific copy. */
export enum ApplyPolicyLeaveErrorKeys {
  POLICY_NOT_ASSIGNED = "LEAVE_ERROR_POLICY_LEAVE_POLICY_NOT_ASSIGNED",
  INSUFFICIENT_BALANCE = "LEAVE_ERROR_POLICY_LEAVE_INSUFFICIENT_BALANCE",
  NOT_APPLICABLE = "LEAVE_ERROR_POLICY_LEAVE_NOT_APPLICABLE",
  REQUEST_OVERLAP = "LEAVE_ERROR_POLICY_LEAVE_REQUEST_OVERLAP",
  OUTSIDE_POLICY_PERIOD = "LEAVE_ERROR_POLICY_LEAVE_OUTSIDE_POLICY_PERIOD"
}
