export enum PolicyLeaveReviewModalEnums {
  DECLINE = "DECLINE",
  APPROVED_STATUS = "APPROVED_STATUS",
  DECLINE_STATUS = "DECLINE_STATUS",
  CANCEL_REQUEST_POPUP = "CANCEL_REQUEST_POPUP",
  CANCELLED_SUMMARY = "CANCELLED_SUMMARY",
  SUPERVISOR_NUDGED = "SUPERVISOR_NUDGED"
}
