export enum PolicyLeaveReviewModalEnums {
  NONE = "",
  DECLINE = "DECLINE",
  APPROVED_STATUS = "APPROVED_STATUS",
  DECLINE_STATUS = "DECLINE_STATUS",
  CANCEL_REQUEST_POPUP = "CANCEL_REQUEST_POPUP",
  CANCELLED_SUMMARY = "CANCELLED_SUMMARY",
  SUPERVISOR_NUDGED = "SUPERVISOR_NUDGED"
}

export enum PolicyLeaveReviewToastEnums {
  APPROVE_SUCCESS = "APPROVE_SUCCESS",
  APPROVE_ERROR = "APPROVE_ERROR",
  DECLINE_SUCCESS = "DECLINE_SUCCESS",
  DECLINE_ERROR = "DECLINE_ERROR",
  REVOKE_SUCCESS = "REVOKE_SUCCESS",
  REVOKE_ERROR = "REVOKE_ERROR",
  CANCEL_SUCCESS = "CANCEL_SUCCESS",
  CANCEL_ERROR = "CANCEL_ERROR",
  NUDGE_SUCCESS = "NUDGE_SUCCESS",
  NUDGE_ERROR = "NUDGE_ERROR"
}
