export const ALLOCATION_PER_PAGE = 6;

export const ALLOCATION_PER_PAGE_MOBILE = 4;

export const LOW_BALANCE_WARNING_DAYS = 5;

export const POLICY_LEAVE_REQUESTS_PER_PAGE = 10;

export const MANAGER_LEAVE_REQUESTS_PER_PAGE = 6;

export const MY_LEAVE_REQUESTS_PER_PAGE = 4;

export const LEAVE_REQUESTS_SKELETON_ROWS = 5;

export const MAX_ALLOWED_UPLOADS = 5;

export const MAX_CUSTOM_LEAVE_ALLOCATION_DAYS_ALLOWED = 360;

export const MIN_CUSTOM_LEAVE_ALLOCATION_DAYS_ALLOWED = 0.5;

export const MAX_POLICY_LEAVE_COMMENT_LENGTH = 255;

export const ATTACHMENT_UPLOAD_FAILED = "ATTACHMENT_UPLOAD_FAILED";

export const SUCCESS_TOAST_DURATION_MS = 4000;

export const TOTAL_PERCENTAGE = 100;
