import ROUTES from "../../common/constants/routes";

export const drawerHiddenProtectedRoutes = [
  ROUTES.ORGANIZATION.SETUP,
  ROUTES.AUTH.RESET_PASSWORD,
  ROUTES.AUTH.VERIFY,
  ROUTES.AUTH.VERIFY_SUCCESS,
  ROUTES.AUTH.VERIFY_RESET_PASSWORD,
  ROUTES.AUTH.VERIFY_GUEST,
  ROUTES.AUTH.VERIFY_GUEST_OTP,
  ROUTES.SETTINGS.PAYMENT,
  ROUTES.REMOVE_PEOPLE,
  ROUTES.CHANGE_SUPERVISORS,
  ROUTES.SUBSCRIPTION,
  ROUTES.SIGN.SIGN,
  ROUTES.SIGN.CREATE_TEMPLATE,
  ROUTES.SIGN.EDIT_TEMPLATE.BASE,
  ROUTES.SIGN.REVIEW,
  ROUTES.SIGN.INFO,
  ROUTES.SIGN.CREATE_DOCUMENT,
  ROUTES.SIGN.SENT_INFO.BASE,
  ROUTES.SIGN.INBOX_INFO.BASE,
  ROUTES.SIGN.DOCUMENT_ACCESS,
  ROUTES.INVOICE.CREATE.BASE,
  ROUTES.INVOICE.VIEW.BASE,
  ROUTES.INVOICE.CUSTOMERS.PROJECTS.BASE
];
