export const COMMON_ERROR_TOKEN_EXPIRED = "COMMON_ERROR_TOKEN_EXPIRED";
export const COMMON_ERROR_CANNOT_USE_PREVIOUS_PASSWORDS =
  "COMMON_ERROR_CANNOT_USE_PREVIOUS_PASSWORDS";
export const COMMON_ERROR_SAME_PASSWORD = "COMMON_ERROR_SAME_PASSWORD";
export const COMMON_ERROR_SYSTEM_VERSION_MISMATCH =
  "COMMON_ERROR_SYSTEM_VERSION_MISMATCH";
export const COMMON_ERROR_USER_VERSION_MISMATCH =
  "COMMON_ERROR_USER_VERSION_MISMATCH";
export const COMMON_ERROR_INVALID_TOKEN = "COMMON_ERROR_INVALID_TOKEN";
export const COMMON_ERROR_ACCESS_DENIED = "COMMON_ERROR_ACCESS_DENIED";
export const COMMON_ERROR_MISSING_COOKIE_IN_TOKEN =
  "COMMON_ERROR_MISSING_COOKIE_IN_TOKEN";
export const COMMON_ERROR_INVALID_REFRESH_TOKEN =
  "COMMON_ERROR_INVALID_REFRESH_TOKEN";
export const LEAVE_ERROR_NUMBER_OF_DAYS_CANNOT_BE_LESS_THAN_USED_DAYS =
  "LEAVE_ERROR_NUMBER_OF_DAYS_CANNOT_BE_LESS_THAN_USED_DAYS";
export const LEAVE_ERROR_LEAVE_POLICY_ALREADY_EXISTS =
  "LEAVE_ERROR_LEAVE_POLICY_ALREADY_EXISTS";
export const LEAVE_ERROR_POLICY_LEAVE_TYPE_ALREADY_EXISTS =
  "LEAVE_ERROR_POLICY_LEAVE_TYPE_ALREADY_EXISTS";
export const COMMON_ERROR_OLD_PASSWORD_INCORRECT =
  "COMMON_ERROR_OLD_PASSWORD_INCORRECT";
export const EP_COMMON_ERROR_DOCUMENT_NAME_ALREADY_EXISTS =
  "EP_COMMON_ERROR_DOCUMENT_NAME_ALREADY_EXISTS";
export const TIME_ERROR_TIME_REQUEST_CANNOT_EDIT =
  "TIME_ERROR_TIME_REQUEST_CANNOT_EDIT";

export const TIME_ERROR_MANUAL_ENTRY_RESTRICTED =
  "TIME_ERROR_MANUAL_ENTRY_RESTRICTED";

export const EP_TIME_ERROR_DIRECT_ENTRY_REQUEST_ALREADY_RESOLVED =
  "EP_TIME_ERROR_DIRECT_ENTRY_REQUEST_ALREADY_RESOLVED";

export const PEOPLE_ERROR_NO_MANAGERS_FOUND = "PEOPLE_ERROR_NO_MANAGERS_FOUND";
