export const DEAL_PAGE_SIZE = 15;
export const DEAL_SEARCH_DEBOUNCE_DELAY = 300;
export const TABLE_CONTAINER_WIDTH_OFFSET = 8;

export const DEAL_TABLE_COLUMN_WIDTH_RATIO = {
  DEAL_NAME: 0.2337,
  VALUE: 0.1532,
  STAGE: 0.1532,
  COMPANY_NAME: 0.1532,
  CONTACT_NAME: 0.1532,
  DEAL_OWNER: 0.1532
};

export const DEAL_NAME_MAX_LENGTH = 255;
export const DEAL_DESCRIPTION_MAX_LENGTH = 2000;
export const DEAL_KANBAN_PAGE_SIZE = 20;

export const CRM_ERROR_DEAL_EXISTS = "CRM_ERROR_DEAL_EXISTS";
