package com.skapp.community.crmplanner.type;

public enum CrmIndustry {

	NONE, ACCOMMODATION_SERVICES, ADMINISTRATIVE_AND_SUPPORT_SERVICES, CONSTRUCTION, CONSUMER_SERVICES, EDUCATION,
	ENTERTAINMENT_PROVIDERS, FARMING_RANCHING_FORESTRY, FINANCIAL_SERVICES, GOVERNMENT_ADMINISTRATION,
	HOLDING_COMPANIES, HOSPITALS_AND_HEALTH_CARE, MANUFACTURING, OIL_GAS_AND_MINING, PROFESSIONAL_SERVICES,
	REAL_ESTATE_AND_EQUIPMENT_RENTAL_SERVICES, RETAIL, TECHNOLOGY_INFORMATION_AND_MEDIA,
	TRANSPORTATION_LOGISTICS_SUPPLY_CHAIN_AND_STORAGE, UTILITIES, WHOLESALE

}
